# Generated by Django 5.1.2 on 2024-10-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_funcionarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDeFutebol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=100)),
                ('nome_time', models.CharField(max_length=100)),
                ('Salario', models.IntegerField()),
            ],
        ),
    ]
